modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "gag"
version = "${version}"
displayName = "Gadgets Against Grind"
authors = "MaxNeedsSnacks"
description = '''
A cross-platform Minecraft mod that adds various different utility items and blocks!
'''
#logoFile = ""

[[dependencies.gag]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gag]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gag]]
modId = "architectury"
mandatory = true
versionRange = "[6.4.62,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.gag]]
modId = "ftblibrary"
mandatory = true
versionRange = "[1902.3.11-build.166,)"
ordering = "AFTER"
side = "BOTH"